kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: observability
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30300
        hostPort: 3000
        protocol: TCP
  - role: worker
  - role: worker
