apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: student-jlgore-dev

resources:
  - ../../base
  - namespace.yaml

components:
  - ../../components/uptime-kuma
  - ../../components/network-policy
