apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: student-jlgore-prod

resources:
  - ../../base
  - namespace.yaml

components:
  - ../../components/network-policy

patches:
  - target:
      kind: Deployment
      name: student-app
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
