apiVersion: v1
kind: Service
metadata:
  name: course-metrics-exporter
  labels:
    app: course-metrics-exporter
spec:
  selector:
    app: course-metrics-exporter
  ports:
    - port: 9100
      targetPort: 9100
      protocol: TCP
      name: metrics
