apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: student-jlgore-dev

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - app-config.yaml
  - redis-secret.yaml
  - redis-configmap.yaml
  - redis-statefulset.yaml
  - redis-service.yaml
