apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  labels:
    app: redis
    student: jlgore
data:
  redis.conf: |
    requirepass redis-lab-password
    appendonly yes
    appendfsync everysec
    maxmemory 64mb
    maxmemory-policy allkeys-lru
    bind 0.0.0.0
